apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-pv
          env:
            - name: GF_SERVER_ROOT_URL
              value: https://grafana.chik4ge.me
            - name: GF_SERVER_ENABLE_GZIP
              value: "true"
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"
            - name: GF_AUTH_GITHUB_ENABLED
              value: "true"
            - name: GF_AUTH_GITHUB_CLIENT_ID
              value: Ov23liEAZPnCVaDnDWdl
            - name: GF_AUTH_GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: github-sso-client-secret
            - name: GF_AUTH_GITHUB_AUTH_URL
              value: https://github.com/login/oauth/authorize
            - name: GF_AUTH_GITHUB_TOKEN_URL
              value: https://github.com/login/oauth/access_token
            - name: GF_AUTH_GITHUB_API_URL
              value: https://api.github.com/user
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc
